version: "3.9"
services:
  my_frontend:
    build: 
      context: .
      dockerfile: Frontend-Dockerfile
    ports:
      - "8007:8007"
    environment:
      - frontend_port=${frontend_port}
      - order_host=${order_host}
      - order_PORT=${order_PORT}
      - catalog_host=${catalog_host}
      - catalog_PORT=${catalog_PORT}
  my_order:
    build: 
      context: .
      dockerfile: Order-Dockerfile
    volumes:
      - ./Order:/Order
    environment:
      - order_csv_file=/Order/order.csv
      - order_host=${order_host}
      - order_PORT=${order_PORT}
      - catalog_host=${catalog_host}
      - catalog_PORT=${catalog_PORT}
  my_catalog:
    build: 
      context: .
      dockerfile: Catalog-Dockerfile
    volumes:
      - ./Catalog:/Catalog
    environment:
      - catalog_PORT=${catalog_PORT}
      - catalog_csv_file=/Catalog/catalog.csv 